/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CartRouteImport } from './routes/cart'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestSigninRouteImport } from './routes/_guest/signin'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as ProductsProductIdIndexRouteImport } from './routes/products/$productId/index'
import { Route as AuthenticatedAdminDashboardIndexRouteImport } from './routes/_authenticated/_admin/dashboard/index'
import { Route as AuthenticatedOrdersOrderidSuccessRouteImport } from './routes/_authenticated/orders/$orderid/success'
import { Route as AuthenticatedOrdersOrderidFailureRouteImport } from './routes/_authenticated/orders/$orderid/failure'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSigninRoute = GuestSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ProductsProductIdIndexRoute = ProductsProductIdIndexRouteImport.update({
  id: '/products/$productId/',
  path: '/products/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDashboardIndexRoute =
  AuthenticatedAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedOrdersOrderidSuccessRoute =
  AuthenticatedOrdersOrderidSuccessRouteImport.update({
    id: '/orders/$orderid/success',
    path: '/orders/$orderid/success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderidFailureRoute =
  AuthenticatedOrdersOrderidFailureRouteImport.update({
    id: '/orders/$orderid/failure',
    path: '/orders/$orderid/failure',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/signin': typeof GuestSigninRoute
  '/signup': typeof GuestSignupRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/orders/$orderid/failure': typeof AuthenticatedOrdersOrderidFailureRoute
  '/orders/$orderid/success': typeof AuthenticatedOrdersOrderidSuccessRoute
  '/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/signin': typeof GuestSigninRoute
  '/signup': typeof GuestSignupRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
  '/orders/$orderid/failure': typeof AuthenticatedOrdersOrderidFailureRoute
  '/orders/$orderid/success': typeof AuthenticatedOrdersOrderidSuccessRoute
  '/dashboard': typeof AuthenticatedAdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_guest/signin': typeof GuestSigninRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/_authenticated/orders/$orderid/failure': typeof AuthenticatedOrdersOrderidFailureRoute
  '/_authenticated/orders/$orderid/success': typeof AuthenticatedOrdersOrderidSuccessRoute
  '/_authenticated/_admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/search'
    | '/unauthorized'
    | '/checkout'
    | '/signin'
    | '/signup'
    | '/products/$productId/'
    | '/orders/$orderid/failure'
    | '/orders/$orderid/success'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/search'
    | '/unauthorized'
    | '/checkout'
    | '/signin'
    | '/signup'
    | '/products/$productId'
    | '/orders/$orderid/failure'
    | '/orders/$orderid/success'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_guest'
    | '/cart'
    | '/search'
    | '/unauthorized'
    | '/_authenticated/_admin'
    | '/_authenticated/checkout'
    | '/_guest/signin'
    | '/_guest/signup'
    | '/products/$productId/'
    | '/_authenticated/orders/$orderid/failure'
    | '/_authenticated/orders/$orderid/success'
    | '/_authenticated/_admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  CartRoute: typeof CartRoute
  SearchRoute: typeof SearchRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/signin': {
      id: '/_guest/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof GuestSigninRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/products/$productId/': {
      id: '/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof ProductsProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/dashboard/': {
      id: '/_authenticated/_admin/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedAdminDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/orders/$orderid/success': {
      id: '/_authenticated/orders/$orderid/success'
      path: '/orders/$orderid/success'
      fullPath: '/orders/$orderid/success'
      preLoaderRoute: typeof AuthenticatedOrdersOrderidSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderid/failure': {
      id: '/_authenticated/orders/$orderid/failure'
      path: '/orders/$orderid/failure'
      fullPath: '/orders/$orderid/failure'
      preLoaderRoute: typeof AuthenticatedOrdersOrderidFailureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardIndexRoute: typeof AuthenticatedAdminDashboardIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardIndexRoute: AuthenticatedAdminDashboardIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedOrdersOrderidFailureRoute: typeof AuthenticatedOrdersOrderidFailureRoute
  AuthenticatedOrdersOrderidSuccessRoute: typeof AuthenticatedOrdersOrderidSuccessRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedOrdersOrderidFailureRoute:
    AuthenticatedOrdersOrderidFailureRoute,
  AuthenticatedOrdersOrderidSuccessRoute:
    AuthenticatedOrdersOrderidSuccessRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestSigninRoute: typeof GuestSigninRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSigninRoute: GuestSigninRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  CartRoute: CartRoute,
  SearchRoute: SearchRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
