export enum ErrorType {
	AUTHENTICATION = "AUTHENTICATION",
	AUTHORIZATION = "AUTHORIZATION",
	BAD_REQUEST = "BAD_REQUEST",
	CACHE_CAPACITY_ERROR = "CACHE_CAPACITY_ERROR",
	CACHE_CONNECTION_ERROR = "CACHE_CONNECTION_ERROR",
	CACHE_ERROR = "CACHE_ERROR",
	CONFLICT = "CONFLICT",
	DATABASE_ERROR = "DATABASE_ERROR",
	EMPTY_CART = "EMPTY_CART",

	INTERNAL = "INTERNAL",

	JWT_EXPIRATION = "JWT_EXPIRATION_ERROR",
	JWT_GENERATION = "JWT_GENERATION_ERROR",
	JWT_INVALID_PAYLOAD = "JWT_INVALID_PAYLOAD_ERROR",
	JWT_INVALID_TOKEN = "JWT_INVALID_TOKEN_ERROR",
	JWT_VERIFICATION = "JWT_VERIFICATION_ERROR",

	NOT_FOUND = "NOT_FOUND",
	PSW_HASH = "PASSWORD_HASH",
	PSW_VALIDATE = "PASSWORD_VALIDATE",
	PSW_VERIFY = "PASSWORD_VERIFY",

	RATE_LIMIT = "RATE_LIMIT",

	VALIDATION = "VALIDATION",
}

export interface ErrorResponse {
	code: string;
	details?: Record<string, unknown>;
	message: string;
	path: string;
	timestamp: string;
}
