export enum ErrorType {
	AUTHENTICATION = "AUTHENTICATION",
	AUTHORIZATION = "AUTHORIZATION",
	BAD_REQUEST = "BAD_REQUEST",
	CACHE_CAPACITY_ERROR = "CACHE_CAPACITY_ERROR",
	CACHE_CONNECTION_ERROR = "CACHE_CONNECTION_ERROR",
	CACHE_ERROR = "CACHE_ERROR",
	CONFLICT = "CONFLICT",
	DATABASE_ERROR = "DATABASE_ERROR",
	EMPTY_CART = "EMPTY_CART",

	INTERNAL = "INTERNAL",
	NOT_FOUND = "NOT_FOUND",

	PSW_HASH = "PASSWORD_HASH",
	PSW_VALIDATE = "PASSWORD_VALIDATE",
	PSW_VERIFY = "PASSWORD_VERIFY",

	RATE_LIMIT = "RATE_LIMIT",

	VALIDATION = "VALIDATION",
}

export interface ErrorResponse {
	code: string;
	details?: Record<string, unknown>;
	message: string;
	path: string;
	timestamp: string;
}
